import { InfoIcon } from 'lucide-react';

import { cn } from '@/lib/utils';

/**
 * Web twin of apps/mobile's ContentDisclaimer: same `contentClass` vocabulary
 * and the same copy, so a derivative reads the same on both clients.
 */
export type ContentClass = 'official_text' | 'ai_generated' | 'community' | 'user_private';

const DISCLAIMER_CONFIG: Record<ContentClass, { text: string; className: string }> = {
  official_text: {
    text: 'This is an official text sourced from a Philippine government publication.',
    className: 'border-blue-200 bg-blue-50 text-blue-800',
  },
  ai_generated: {
    text: 'This content was generated by AI. It may contain errors. Verify with official sources.',
    className: 'border-warm-accent/40 bg-warm-accent-soft text-warm-accent-deep',
  },
  community: {
    text: 'This content was contributed by a community member and has not been independently verified.',
    className: 'border-gray-300 bg-gray-50 text-gray-700',
  },
  user_private: {
    text: 'This is your private content. It is not visible to others.',
    className: 'border-emerald-200 bg-emerald-50 text-emerald-800',
  },
};

export function ContentDisclaimer({
  contentClass,
  className,
}: {
  contentClass: ContentClass;
  className?: string;
}) {
  const config = DISCLAIMER_CONFIG[contentClass];
  return (
    <div
      role="note"
      data-testid="content-disclaimer"
      className={cn(
        'flex items-start gap-2 rounded-md border px-3 py-2 text-xs leading-5',
        config.className,
        className,
      )}
    >
      <InfoIcon className="mt-0.5 size-3.5 shrink-0" aria-hidden />
      <span>{config.text}</span>
    </div>
  );
}
