import { Injectable, Logger } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
} from 'docx';

// ---------------------------------------------------------------------------
// Types for content passed to generator
// ---------------------------------------------------------------------------

export interface DigestExportData {
  title: string;
  court?: string | null;
  grNo?: string | null;
  ponente?: string | null;
  decisionDate?: Date | null;
  digestType: string;
  summary?: string | null;
  facts?: string | null;
  petitionerArguments?: string | null;
  respondentArguments?: string | null;
  issues?: string | null;
  ruling?: string | null;
  doctrine?: string | null;
  dispositive?: string | null;
  citedAuthoritiesJson: unknown[];
}

export interface MemoExportData {
  query: string;
  memoType: string;
  structuredOutput: Record<string, unknown> | null;
  citationsJson: unknown[];
  confidenceScore?: number | null;
}

export interface NoteExportData {
  title?: string | null;
  body: unknown; // Tiptap JSON
  matterTitle?: string | null;
}

// ---------------------------------------------------------------------------
// Helper: safe filename
// ---------------------------------------------------------------------------

function safeName(title: string, suffix: string, ext: string): string {
  const clean = title.replace(/[^a-zA-Z0-9 _-]/g, '').trim().slice(0, 80) || 'export';
  return `${clean}-${suffix}.${ext}`;
}

// ---------------------------------------------------------------------------
// Helper: extract plain text from Tiptap JSON
// ---------------------------------------------------------------------------

function extractTextFromTiptap(node: unknown): string {
  if (!node || typeof node !== 'object') return '';
  const n = node as Record<string, unknown>;
  if (n['type'] === 'text' && typeof n['text'] === 'string') {
    return n['text'];
  }
  if (Array.isArray(n['content'])) {
    return (n['content'] as unknown[]).map(extractTextFromTiptap).join('');
  }
  return '';
}

function extractParagraphs(body: unknown): string[] {
  if (!body || typeof body !== 'object') return [];
  const doc = body as Record<string, unknown>;
  if (!Array.isArray(doc['content'])) return [];

  const paragraphs: string[] = [];
  for (const block of doc['content'] as unknown[]) {
    const text = extractTextFromTiptap(block).trim();
    if (text) paragraphs.push(text);
  }
  return paragraphs;
}

// ---------------------------------------------------------------------------
// Helper: format date
// ---------------------------------------------------------------------------

function formatDate(d: Date | string | null | undefined): string {
  if (!d) return '';
  const date = d instanceof Date ? d : new Date(d);
  return date.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
}

// ---------------------------------------------------------------------------
// PDF helpers
// ---------------------------------------------------------------------------

const FOOTER_TEXT = 'Generated by LIBERTASIAN \u2014 Philippine Legal AI Platform';
const EXPORT_DATE = () =>
  new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

function pdfSection(doc: PDFKit.PDFDocument, label: string, text: string | null | undefined) {
  if (!text) return;
  if (doc.y > doc.page.height - 120) doc.addPage();
  doc.fontSize(11).font('Helvetica-Bold').fillColor('#1a56db').text(label);
  doc.fillColor('#000000');
  doc.moveDown(0.2);
  doc.fontSize(10).font('Helvetica').text(text, { lineGap: 2 });
  doc.moveDown(0.6);
}

function pdfFooter(doc: PDFKit.PDFDocument) {
  doc.moveDown(1);
  doc.fontSize(7).font('Helvetica').fillColor('#aaaaaa').text(FOOTER_TEXT, { align: 'center' });
}

// ---------------------------------------------------------------------------
// DOCX helpers
// ---------------------------------------------------------------------------

function docxHeading(text: string, level: (typeof HeadingLevel)[keyof typeof HeadingLevel] = HeadingLevel.HEADING_1): Paragraph {
  return new Paragraph({
    text,
    heading: level,
    alignment: AlignmentType.CENTER,
    spacing: { after: 100 },
  });
}

function docxMeta(text: string): Paragraph {
  return new Paragraph({
    children: [new TextRun({ text, color: '888888', size: 18 })],
    alignment: AlignmentType.CENTER,
    spacing: { after: 200 },
    border: { bottom: { style: BorderStyle.SINGLE, size: 1, color: 'cccccc' } },
  });
}

function docxSectionLabel(label: string): Paragraph {
  return new Paragraph({
    children: [new TextRun({ text: label, bold: true, color: '1a56db', size: 22 })],
    spacing: { before: 200, after: 60 },
  });
}

function docxBody(text: string): Paragraph {
  return new Paragraph({
    children: [new TextRun({ text, size: 20 })],
    spacing: { after: 120 },
  });
}

function docxFooter(): Paragraph {
  return new Paragraph({
    children: [new TextRun({ text: FOOTER_TEXT, color: 'aaaaaa', size: 14 })],
    alignment: AlignmentType.CENTER,
    spacing: { before: 400 },
  });
}

// ---------------------------------------------------------------------------
// Service
// ---------------------------------------------------------------------------

@Injectable()
export class ExportGeneratorService {
  private readonly logger = new Logger(ExportGeneratorService.name);

  // =======================================================================
  // DIGEST — PDF
  // =======================================================================

  async generateDigestPdf(data: DigestExportData): Promise<{ buffer: Buffer; filename: string }> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({
        size: 'LETTER',
        margins: { top: 60, bottom: 60, left: 60, right: 60 },
        info: { Title: data.title, Author: 'LIBERTASIAN', Subject: 'Case Digest Export' },
      });

      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => {
        const buffer = Buffer.concat(chunks);
        resolve({ buffer, filename: safeName(data.title, 'digest', 'pdf') });
      });
      doc.on('error', reject);

      // Title
      doc.fontSize(18).font('Helvetica-Bold').text(data.title, { align: 'center' });
      doc.moveDown(0.3);

      // Meta line
      const meta = [
        data.court,
        data.grNo ? `G.R. No. ${data.grNo}` : null,
        data.ponente ? `Ponente: ${data.ponente}` : null,
        data.decisionDate ? formatDate(data.decisionDate) : null,
        `Type: ${data.digestType.replace(/_/g, ' ')}`,
        `Exported: ${EXPORT_DATE()}`,
      ].filter(Boolean).join('  |  ');

      doc.fontSize(9).font('Helvetica').fillColor('#888888').text(meta, { align: 'center' });
      doc.fillColor('#000000');
      doc.moveDown(1);
      doc.moveTo(60, doc.y).lineTo(doc.page.width - 60, doc.y).strokeColor('#cccccc').stroke();
      doc.moveDown(1);

      // Sections
      pdfSection(doc, 'Summary', data.summary);
      pdfSection(doc, 'Facts', data.facts);
      pdfSection(doc, 'Petitioner Arguments', data.petitionerArguments);
      pdfSection(doc, 'Respondent Arguments', data.respondentArguments);
      pdfSection(doc, 'Issues', data.issues);
      pdfSection(doc, 'Ruling', data.ruling);
      pdfSection(doc, 'Doctrine', data.doctrine);
      pdfSection(doc, 'Dispositive Portion', data.dispositive);

      // Cited Authorities
      if (Array.isArray(data.citedAuthoritiesJson) && data.citedAuthoritiesJson.length > 0) {
        if (doc.y > doc.page.height - 120) doc.addPage();
        doc.fontSize(11).font('Helvetica-Bold').fillColor('#1a56db').text('Cited Authorities');
        doc.fillColor('#000000');
        doc.moveDown(0.2);
        for (const cite of data.citedAuthoritiesJson) {
          const c = cite as Record<string, unknown>;
          const text = (c['citation_text'] ?? c['citationText'] ?? c['title'] ?? JSON.stringify(cite)) as string;
          doc.fontSize(9).font('Helvetica').text(`\u2022 ${text}`, { indent: 10 });
        }
        doc.moveDown(0.6);
      }

      pdfFooter(doc);
      doc.end();
    });
  }

  // =======================================================================
  // DIGEST — DOCX
  // =======================================================================

  async generateDigestDocx(data: DigestExportData): Promise<{ buffer: Buffer; filename: string }> {
    const children: Paragraph[] = [];

    children.push(docxHeading(data.title));

    const meta = [
      data.court,
      data.grNo ? `G.R. No. ${data.grNo}` : null,
      data.ponente ? `Ponente: ${data.ponente}` : null,
      data.decisionDate ? formatDate(data.decisionDate) : null,
      `Type: ${data.digestType.replace(/_/g, ' ')}`,
      `Exported: ${EXPORT_DATE()}`,
    ].filter(Boolean).join('  |  ');
    children.push(docxMeta(meta));

    const sections: [string, string | null | undefined][] = [
      ['Summary', data.summary],
      ['Facts', data.facts],
      ['Petitioner Arguments', data.petitionerArguments],
      ['Respondent Arguments', data.respondentArguments],
      ['Issues', data.issues],
      ['Ruling', data.ruling],
      ['Doctrine', data.doctrine],
      ['Dispositive Portion', data.dispositive],
    ];

    for (const [label, text] of sections) {
      if (!text) continue;
      children.push(docxSectionLabel(label));
      children.push(docxBody(text));
    }

    if (Array.isArray(data.citedAuthoritiesJson) && data.citedAuthoritiesJson.length > 0) {
      children.push(docxSectionLabel('Cited Authorities'));
      for (const cite of data.citedAuthoritiesJson) {
        const c = cite as Record<string, unknown>;
        const text = (c['citation_text'] ?? c['citationText'] ?? c['title'] ?? JSON.stringify(cite)) as string;
        children.push(
          new Paragraph({
            children: [new TextRun({ text: `\u2022 ${text}`, size: 18 })],
            spacing: { after: 40 },
            indent: { left: 200 },
          }),
        );
      }
    }

    children.push(docxFooter());

    const doc = new Document({ sections: [{ children }] });
    const buffer = await Packer.toBuffer(doc);
    return { buffer: Buffer.from(buffer), filename: safeName(data.title, 'digest', 'docx') };
  }

  // =======================================================================
  // MEMO — PDF
  // =======================================================================

  async generateMemoPdf(data: MemoExportData): Promise<{ buffer: Buffer; filename: string }> {
    const title = `Legal Memo: ${data.query.slice(0, 100)}`;

    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({
        size: 'LETTER',
        margins: { top: 60, bottom: 60, left: 60, right: 60 },
        info: { Title: title, Author: 'LIBERTASIAN', Subject: 'Legal Memo Export' },
      });

      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => {
        const buffer = Buffer.concat(chunks);
        resolve({ buffer, filename: safeName(data.query, 'memo', 'pdf') });
      });
      doc.on('error', reject);

      // Title
      doc.fontSize(18).font('Helvetica-Bold').text('Legal Memo', { align: 'center' });
      doc.moveDown(0.3);

      // Meta
      const meta = [
        `Type: ${data.memoType.replace(/_/g, ' ')}`,
        data.confidenceScore != null ? `Confidence: ${Math.round(data.confidenceScore * 100)}%` : null,
        `Exported: ${EXPORT_DATE()}`,
      ].filter(Boolean).join('  |  ');
      doc.fontSize(9).font('Helvetica').fillColor('#888888').text(meta, { align: 'center' });
      doc.fillColor('#000000');
      doc.moveDown(1);
      doc.moveTo(60, doc.y).lineTo(doc.page.width - 60, doc.y).strokeColor('#cccccc').stroke();
      doc.moveDown(1);

      // Query
      pdfSection(doc, 'Query', data.query);

      // Structured output sections
      if (data.structuredOutput && typeof data.structuredOutput === 'object') {
        const output = data.structuredOutput as Record<string, unknown>;
        for (const [key, value] of Object.entries(output)) {
          if (typeof value === 'string' && value.trim()) {
            const label = key.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
            pdfSection(doc, label, value);
          }
        }
      }

      // Citations
      if (Array.isArray(data.citationsJson) && data.citationsJson.length > 0) {
        if (doc.y > doc.page.height - 120) doc.addPage();
        doc.fontSize(11).font('Helvetica-Bold').fillColor('#1a56db').text('Citations');
        doc.fillColor('#000000');
        doc.moveDown(0.2);
        for (const cite of data.citationsJson) {
          const c = cite as Record<string, unknown>;
          const text = (c['citation_text'] ?? c['citationText'] ?? c['title'] ?? JSON.stringify(cite)) as string;
          doc.fontSize(9).font('Helvetica').text(`\u2022 ${text}`, { indent: 10 });
        }
        doc.moveDown(0.6);
      }

      pdfFooter(doc);
      doc.end();
    });
  }

  // =======================================================================
  // MEMO — DOCX
  // =======================================================================

  async generateMemoDocx(data: MemoExportData): Promise<{ buffer: Buffer; filename: string }> {
    const children: Paragraph[] = [];

    children.push(docxHeading('Legal Memo'));

    const meta = [
      `Type: ${data.memoType.replace(/_/g, ' ')}`,
      data.confidenceScore != null ? `Confidence: ${Math.round(data.confidenceScore * 100)}%` : null,
      `Exported: ${EXPORT_DATE()}`,
    ].filter(Boolean).join('  |  ');
    children.push(docxMeta(meta));

    children.push(docxSectionLabel('Query'));
    children.push(docxBody(data.query));

    if (data.structuredOutput && typeof data.structuredOutput === 'object') {
      const output = data.structuredOutput as Record<string, unknown>;
      for (const [key, value] of Object.entries(output)) {
        if (typeof value === 'string' && value.trim()) {
          const label = key.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
          children.push(docxSectionLabel(label));
          children.push(docxBody(value));
        }
      }
    }

    if (Array.isArray(data.citationsJson) && data.citationsJson.length > 0) {
      children.push(docxSectionLabel('Citations'));
      for (const cite of data.citationsJson) {
        const c = cite as Record<string, unknown>;
        const text = (c['citation_text'] ?? c['citationText'] ?? c['title'] ?? JSON.stringify(cite)) as string;
        children.push(
          new Paragraph({
            children: [new TextRun({ text: `\u2022 ${text}`, size: 18 })],
            spacing: { after: 40 },
            indent: { left: 200 },
          }),
        );
      }
    }

    children.push(docxFooter());

    const doc = new Document({ sections: [{ children }] });
    const buffer = await Packer.toBuffer(doc);
    return { buffer: Buffer.from(buffer), filename: safeName(data.query, 'memo', 'docx') };
  }

  // =======================================================================
  // NOTE — PDF
  // =======================================================================

  async generateNotePdf(data: NoteExportData): Promise<{ buffer: Buffer; filename: string }> {
    const noteTitle = data.title || 'Untitled Note';

    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({
        size: 'LETTER',
        margins: { top: 60, bottom: 60, left: 60, right: 60 },
        info: { Title: noteTitle, Author: 'LIBERTASIAN', Subject: 'Note Export' },
      });

      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => {
        const buffer = Buffer.concat(chunks);
        resolve({ buffer, filename: safeName(noteTitle, 'note', 'pdf') });
      });
      doc.on('error', reject);

      // Title
      doc.fontSize(18).font('Helvetica-Bold').text(noteTitle, { align: 'center' });
      doc.moveDown(0.3);

      // Meta
      const meta = [
        data.matterTitle ? `Matter: ${data.matterTitle}` : null,
        `Exported: ${EXPORT_DATE()}`,
      ].filter(Boolean).join('  |  ');
      doc.fontSize(9).font('Helvetica').fillColor('#888888').text(meta, { align: 'center' });
      doc.fillColor('#000000');
      doc.moveDown(1);
      doc.moveTo(60, doc.y).lineTo(doc.page.width - 60, doc.y).strokeColor('#cccccc').stroke();
      doc.moveDown(1);

      // Body paragraphs
      const paragraphs = extractParagraphs(data.body);
      if (paragraphs.length > 0) {
        for (const para of paragraphs) {
          if (doc.y > doc.page.height - 100) doc.addPage();
          doc.fontSize(10).font('Helvetica').text(para, { lineGap: 2 });
          doc.moveDown(0.4);
        }
      } else {
        doc.fontSize(10).font('Helvetica').fillColor('#888888').text('(No content)');
        doc.fillColor('#000000');
      }

      pdfFooter(doc);
      doc.end();
    });
  }

  // =======================================================================
  // NOTE — DOCX
  // =======================================================================

  async generateNoteDocx(data: NoteExportData): Promise<{ buffer: Buffer; filename: string }> {
    const noteTitle = data.title || 'Untitled Note';
    const children: Paragraph[] = [];

    children.push(docxHeading(noteTitle));

    const meta = [
      data.matterTitle ? `Matter: ${data.matterTitle}` : null,
      `Exported: ${EXPORT_DATE()}`,
    ].filter(Boolean).join('  |  ');
    children.push(docxMeta(meta));

    const paragraphs = extractParagraphs(data.body);
    if (paragraphs.length > 0) {
      for (const para of paragraphs) {
        children.push(docxBody(para));
      }
    } else {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: '(No content)', italics: true, color: '888888', size: 20 })],
        }),
      );
    }

    children.push(docxFooter());

    const doc = new Document({ sections: [{ children }] });
    const buffer = await Packer.toBuffer(doc);
    return { buffer: Buffer.from(buffer), filename: safeName(noteTitle, 'note', 'docx') };
  }
}
