import React from 'react';
import { render } from '@testing-library/react-native';

jest.mock('@expo/vector-icons', () => ({
  Ionicons: ({ name }: { name: string }) => {
    const { Text } = require('react-native');
    return <Text>{name}</Text>;
  },
}));

import { ContentDisclaimer } from './content-disclaimer';

describe('ContentDisclaimer', () => {
  it('renders official_text disclaimer', () => {
    const { getByText } = render(<ContentDisclaimer contentClass="official_text" />);
    expect(getByText(/official text sourced from a Philippine government/i)).toBeTruthy();
  });

  it('renders ai_generated disclaimer', () => {
    const { getByText } = render(<ContentDisclaimer contentClass="ai_generated" />);
    expect(getByText(/generated by AI.*may contain errors/i)).toBeTruthy();
  });

  it('renders community disclaimer', () => {
    const { getByText } = render(<ContentDisclaimer contentClass="community" />);
    expect(getByText(/contributed by a community member/i)).toBeTruthy();
  });

  it('renders user_private disclaimer', () => {
    const { getByText } = render(<ContentDisclaimer contentClass="user_private" />);
    expect(getByText(/private content.*not visible to others/i)).toBeTruthy();
  });

  it('renders nothing for unknown content class', () => {
    const { toJSON } = render(<ContentDisclaimer contentClass="unknown_type" />);
    expect(toJSON()).toBeNull();
  });

  it('renders in compact mode', () => {
    const { getByText } = render(<ContentDisclaimer contentClass="official_text" compact />);
    expect(getByText(/official text/i)).toBeTruthy();
  });

  it('renders information icon', () => {
    const { getByText } = render(<ContentDisclaimer contentClass="official_text" />);
    expect(getByText('information-circle-outline')).toBeTruthy();
  });
});
