import { View, Text, StyleSheet } from 'react-native';
import { Ionicons } from '@expo/vector-icons';

interface ContentDisclaimerProps {
  contentClass: string;
  compact?: boolean;
}

const DISCLAIMER_CONFIG: Record<
  string,
  { text: string; color: string; bg: string; border: string }
> = {
  official_text: {
    text: 'This is an official text sourced from a Philippine government publication.',
    color: '#1d4ed8',
    bg: '#eff6ff',
    border: '#bfdbfe',
  },
  ai_generated: {
    text: 'This content was generated by AI. It may contain errors. Verify with official sources.',
    color: '#92400e',
    bg: '#fef3c7',
    border: '#fde68a',
  },
  community: {
    text: 'This content was contributed by a community member and has not been independently verified.',
    color: '#4b5563',
    bg: '#f3f4f6',
    border: '#d1d5db',
  },
  user_private: {
    text: 'This is your private content. It is not visible to others.',
    color: '#065f46',
    bg: '#ecfdf5',
    border: '#a7f3d0',
  },
};

export function ContentDisclaimer({ contentClass, compact }: ContentDisclaimerProps) {
  const config = DISCLAIMER_CONFIG[contentClass];
  if (!config) return null;

  return (
    <View
      style={[
        styles.container,
        { backgroundColor: config.bg, borderColor: config.border },
        compact && styles.containerCompact,
      ]}
    >
      <Ionicons
        name="information-circle-outline"
        size={compact ? 14 : 16}
        color={config.color}
      />
      <Text
        style={[
          styles.text,
          { color: config.color },
          compact && styles.textCompact,
        ]}
        numberOfLines={compact ? 1 : undefined}
      >
        {config.text}
      </Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
  },
  containerCompact: {
    padding: 6,
    gap: 6,
    alignItems: 'center',
  },
  text: {
    fontSize: 13,
    lineHeight: 19,
    flex: 1,
  },
  textCompact: {
    fontSize: 11,
    lineHeight: 15,
  },
});
