import { Injectable, Logger, NotFoundException, ForbiddenException } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  Table,
  TableRow,
  TableCell,
  WidthType,
  ShadingType,
} from 'docx';

import { PrismaService } from '../../prisma/prisma.service';

@Injectable()
export class StudyExportService {
  private readonly logger = new Logger(StudyExportService.name);

  constructor(private readonly prisma: PrismaService) {}

  // =========================================================================
  // Flashcard Set Export
  // =========================================================================

  async exportFlashcardSetPdf(
    setId: string,
    userId: string,
    organizationId: string,
  ): Promise<{ buffer: Buffer; filename: string }> {
    const { set, flashcards } = await this.loadFlashcardSetForExport(setId, userId, organizationId);

    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({
        size: 'LETTER',
        margins: { top: 60, bottom: 60, left: 60, right: 60 },
        info: {
          Title: set.title,
          Author: 'LIBERTASIAN',
          Subject: 'Flashcard Set Export',
        },
      });

      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => {
        const buffer = Buffer.concat(chunks);
        const safeName = set.title.replace(/[^a-zA-Z0-9 _-]/g, '').slice(0, 80);
        resolve({ buffer, filename: `${safeName}-flashcards.pdf` });
      });
      doc.on('error', reject);

      // Title page header
      doc.fontSize(20).font('Helvetica-Bold').text(set.title, { align: 'center' });
      doc.moveDown(0.3);

      if (set.description) {
        doc.fontSize(10).font('Helvetica').fillColor('#555555').text(set.description, { align: 'center' });
        doc.fillColor('#000000');
      }

      doc.moveDown(0.3);
      doc.fontSize(9).font('Helvetica').fillColor('#888888').text(
        [
          set.barSubject ? `Subject: ${set.barSubject.replace(/_/g, ' ')}` : null,
          set.topic ? `Topic: ${set.topic}` : null,
          `${flashcards.length} card${flashcards.length !== 1 ? 's' : ''}`,
          `Exported: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
        ].filter(Boolean).join('  |  '),
        { align: 'center' },
      );
      doc.fillColor('#000000');
      doc.moveDown(1);

      // Separator line
      doc.moveTo(60, doc.y).lineTo(doc.page.width - 60, doc.y).strokeColor('#cccccc').stroke();
      doc.moveDown(1);

      // Cards
      flashcards.forEach((card, index) => {
        // Check if we need a new page (leaving room for the card)
        if (doc.y > doc.page.height - 180) {
          doc.addPage();
        }

        // Card number
        doc.fontSize(9).font('Helvetica-Bold').fillColor('#1a56db').text(`Card ${index + 1}`);
        doc.fillColor('#000000');
        doc.moveDown(0.3);

        // Question
        doc.fontSize(10).font('Helvetica-Bold').text('Q: ', { continued: true });
        doc.font('Helvetica').text(card.front);
        doc.moveDown(0.3);

        // Answer
        doc.fontSize(10).font('Helvetica-Bold').text('A: ', { continued: true });
        doc.font('Helvetica').text(card.back);

        // Source reference
        const sourceRef = this.getFlashcardSourceRef(card);
        if (sourceRef) {
          doc.moveDown(0.2);
          doc.fontSize(8).font('Helvetica-Oblique').fillColor('#888888').text(`Source: ${sourceRef}`);
          doc.fillColor('#000000');
        }

        doc.moveDown(0.5);

        // Separator between cards
        if (index < flashcards.length - 1) {
          doc.moveTo(60, doc.y).lineTo(doc.page.width - 60, doc.y).strokeColor('#eeeeee').stroke();
          doc.moveDown(0.5);
        }
      });

      // Footer
      doc.moveDown(1);
      doc.fontSize(7).font('Helvetica').fillColor('#aaaaaa').text(
        'Generated by LIBERTASIAN — Philippine Legal AI Platform',
        { align: 'center' },
      );

      doc.end();
    });
  }

  async exportFlashcardSetDocx(
    setId: string,
    userId: string,
    organizationId: string,
  ): Promise<{ buffer: Buffer; filename: string }> {
    const { set, flashcards } = await this.loadFlashcardSetForExport(setId, userId, organizationId);

    const children: Paragraph[] = [];

    // Title
    children.push(
      new Paragraph({
        text: set.title,
        heading: HeadingLevel.HEADING_1,
        alignment: AlignmentType.CENTER,
        spacing: { after: 100 },
      }),
    );

    // Description
    if (set.description) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: set.description, italics: true, color: '555555', size: 20 }),
          ],
          alignment: AlignmentType.CENTER,
          spacing: { after: 100 },
        }),
      );
    }

    // Metadata line
    const metaParts = [
      set.barSubject ? `Subject: ${set.barSubject.replace(/_/g, ' ')}` : null,
      set.topic ? `Topic: ${set.topic}` : null,
      `${flashcards.length} card${flashcards.length !== 1 ? 's' : ''}`,
      `Exported: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
    ].filter(Boolean).join('  |  ');

    children.push(
      new Paragraph({
        children: [
          new TextRun({ text: metaParts, color: '888888', size: 18 }),
        ],
        alignment: AlignmentType.CENTER,
        spacing: { after: 300 },
        border: {
          bottom: { style: BorderStyle.SINGLE, size: 1, color: 'cccccc' },
        },
      }),
    );

    // Cards as table
    const tableRows: TableRow[] = [];

    // Table header
    tableRows.push(
      new TableRow({
        tableHeader: true,
        children: [
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: '#', bold: true, size: 20 })] })],
            width: { size: 5, type: WidthType.PERCENTAGE },
            shading: { type: ShadingType.SOLID, color: 'f3f4f6' },
          }),
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: 'Question', bold: true, size: 20 })] })],
            width: { size: 45, type: WidthType.PERCENTAGE },
            shading: { type: ShadingType.SOLID, color: 'f3f4f6' },
          }),
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: 'Answer', bold: true, size: 20 })] })],
            width: { size: 50, type: WidthType.PERCENTAGE },
            shading: { type: ShadingType.SOLID, color: 'f3f4f6' },
          }),
        ],
      }),
    );

    // Card rows
    flashcards.forEach((card, index) => {
      const cellChildren: Paragraph[] = [
        new Paragraph({
          children: [new TextRun({ text: card.back, size: 20 })],
        }),
      ];

      const sourceRef = this.getFlashcardSourceRef(card);
      if (sourceRef) {
        cellChildren.push(
          new Paragraph({
            children: [new TextRun({ text: `Source: ${sourceRef}`, italics: true, color: '888888', size: 16 })],
            spacing: { before: 60 },
          }),
        );
      }

      tableRows.push(
        new TableRow({
          children: [
            new TableCell({
              children: [new Paragraph({ children: [new TextRun({ text: `${index + 1}`, size: 20 })] })],
            }),
            new TableCell({
              children: [new Paragraph({ children: [new TextRun({ text: card.front, size: 20 })] })],
            }),
            new TableCell({ children: cellChildren }),
          ],
        }),
      );
    });

    children.push(
      new Paragraph({ spacing: { before: 200 } }),
    );

    const table = new Table({
      rows: tableRows,
      width: { size: 100, type: WidthType.PERCENTAGE },
    });

    // Footer
    const footer = new Paragraph({
      children: [
        new TextRun({
          text: 'Generated by LIBERTASIAN \u2014 Philippine Legal AI Platform',
          color: 'aaaaaa',
          size: 14,
        }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { before: 400 },
    });

    const doc = new Document({
      sections: [
        {
          children: [...children, table, footer],
        },
      ],
    });

    const buffer = await Packer.toBuffer(doc);
    const safeName = set.title.replace(/[^a-zA-Z0-9 _-]/g, '').slice(0, 80);
    return { buffer: Buffer.from(buffer), filename: `${safeName}-flashcards.docx` };
  }

  // =========================================================================
  // Reviewer Pack Export
  // =========================================================================

  async exportReviewerPackPdf(
    packId: string,
    userId: string,
    organizationId: string,
  ): Promise<{ buffer: Buffer; filename: string }> {
    const { pack, items } = await this.loadReviewerPackForExport(packId, userId, organizationId);

    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({
        size: 'LETTER',
        margins: { top: 60, bottom: 60, left: 60, right: 60 },
        info: {
          Title: pack.title,
          Author: 'LIBERTASIAN',
          Subject: 'Reviewer Pack Export',
        },
      });

      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => {
        const buffer = Buffer.concat(chunks);
        const safeName = pack.title.replace(/[^a-zA-Z0-9 _-]/g, '').slice(0, 80);
        resolve({ buffer, filename: `${safeName}-reviewer-pack.pdf` });
      });
      doc.on('error', reject);

      // Title
      doc.fontSize(20).font('Helvetica-Bold').text(pack.title, { align: 'center' });
      doc.moveDown(0.3);

      if (pack.description) {
        doc.fontSize(10).font('Helvetica').fillColor('#555555').text(pack.description, { align: 'center' });
        doc.fillColor('#000000');
      }

      doc.moveDown(0.3);
      doc.fontSize(9).font('Helvetica').fillColor('#888888').text(
        [
          pack.barSubject ? `Subject: ${pack.barSubject.replace(/_/g, ' ')}` : null,
          pack.topic ? `Topic: ${pack.topic}` : null,
          `${items.length} item${items.length !== 1 ? 's' : ''}`,
          `Exported: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
        ].filter(Boolean).join('  |  '),
        { align: 'center' },
      );
      doc.fillColor('#000000');
      doc.moveDown(1);

      // Separator
      doc.moveTo(60, doc.y).lineTo(doc.page.width - 60, doc.y).strokeColor('#cccccc').stroke();
      doc.moveDown(1);

      // Items
      items.forEach((item, index) => {
        if (doc.y > doc.page.height - 160) {
          doc.addPage();
        }

        // Item number & type
        const typeLabel = item.itemType.replace(/_/g, ' ');
        doc.fontSize(9).font('Helvetica-Bold').fillColor('#1a56db').text(`Item ${index + 1}`);
        doc.fillColor('#000000');
        doc.moveDown(0.2);

        // Type badge
        doc.fontSize(8).font('Helvetica').fillColor('#6b7280').text(`[${typeLabel}]`);
        doc.fillColor('#000000');
        doc.moveDown(0.2);

        // Title
        const title = this.getReviewerItemTitle(item);
        doc.fontSize(11).font('Helvetica-Bold').text(title);

        // Subtitle
        const subtitle = this.getReviewerItemSubtitle(item);
        if (subtitle) {
          doc.fontSize(9).font('Helvetica').fillColor('#6b7280').text(subtitle);
          doc.fillColor('#000000');
        }

        // Note
        if (item.note) {
          doc.moveDown(0.2);
          doc.fontSize(9).font('Helvetica-Oblique').fillColor('#92400e').text(`Note: ${item.note}`);
          doc.fillColor('#000000');
        }

        doc.moveDown(0.5);

        if (index < items.length - 1) {
          doc.moveTo(60, doc.y).lineTo(doc.page.width - 60, doc.y).strokeColor('#eeeeee').stroke();
          doc.moveDown(0.5);
        }
      });

      // Footer
      doc.moveDown(1);
      doc.fontSize(7).font('Helvetica').fillColor('#aaaaaa').text(
        'Generated by LIBERTASIAN \u2014 Philippine Legal AI Platform',
        { align: 'center' },
      );

      doc.end();
    });
  }

  async exportReviewerPackDocx(
    packId: string,
    userId: string,
    organizationId: string,
  ): Promise<{ buffer: Buffer; filename: string }> {
    const { pack, items } = await this.loadReviewerPackForExport(packId, userId, organizationId);

    const children: Paragraph[] = [];

    // Title
    children.push(
      new Paragraph({
        text: pack.title,
        heading: HeadingLevel.HEADING_1,
        alignment: AlignmentType.CENTER,
        spacing: { after: 100 },
      }),
    );

    if (pack.description) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: pack.description, italics: true, color: '555555', size: 20 }),
          ],
          alignment: AlignmentType.CENTER,
          spacing: { after: 100 },
        }),
      );
    }

    const metaParts = [
      pack.barSubject ? `Subject: ${pack.barSubject.replace(/_/g, ' ')}` : null,
      pack.topic ? `Topic: ${pack.topic}` : null,
      `${items.length} item${items.length !== 1 ? 's' : ''}`,
      `Exported: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
    ].filter(Boolean).join('  |  ');

    children.push(
      new Paragraph({
        children: [new TextRun({ text: metaParts, color: '888888', size: 18 })],
        alignment: AlignmentType.CENTER,
        spacing: { after: 300 },
        border: {
          bottom: { style: BorderStyle.SINGLE, size: 1, color: 'cccccc' },
        },
      }),
    );

    // Items
    items.forEach((item, index) => {
      const title = this.getReviewerItemTitle(item);
      const subtitle = this.getReviewerItemSubtitle(item);
      const typeLabel = item.itemType.replace(/_/g, ' ');

      // Item heading
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: `${index + 1}. `, bold: true, color: '1a56db', size: 22 }),
            new TextRun({ text: title, bold: true, size: 22 }),
            new TextRun({ text: `  [${typeLabel}]`, color: '6b7280', size: 18 }),
          ],
          spacing: { before: 200, after: 60 },
        }),
      );

      if (subtitle) {
        children.push(
          new Paragraph({
            children: [new TextRun({ text: subtitle, color: '6b7280', size: 18 })],
            spacing: { after: 60 },
          }),
        );
      }

      if (item.note) {
        children.push(
          new Paragraph({
            children: [
              new TextRun({ text: 'Note: ', bold: true, italics: true, color: '92400e', size: 18 }),
              new TextRun({ text: item.note, italics: true, color: '92400e', size: 18 }),
            ],
            spacing: { after: 60 },
          }),
        );
      }

      // Separator
      if (index < items.length - 1) {
        children.push(
          new Paragraph({
            border: { bottom: { style: BorderStyle.SINGLE, size: 1, color: 'eeeeee' } },
            spacing: { before: 100, after: 100 },
          }),
        );
      }
    });

    // Footer
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: 'Generated by LIBERTASIAN \u2014 Philippine Legal AI Platform',
            color: 'aaaaaa',
            size: 14,
          }),
        ],
        alignment: AlignmentType.CENTER,
        spacing: { before: 400 },
      }),
    );

    const doc = new Document({
      sections: [{ children }],
    });

    const buffer = await Packer.toBuffer(doc);
    const safeName = pack.title.replace(/[^a-zA-Z0-9 _-]/g, '').slice(0, 80);
    return { buffer: Buffer.from(buffer), filename: `${safeName}-reviewer-pack.docx` };
  }

  // =========================================================================
  // Private helpers
  // =========================================================================

  private async loadFlashcardSetForExport(
    setId: string,
    userId: string,
    organizationId: string,
  ) {
    const set = await this.prisma.flashcardSet.findUnique({
      where: { id: setId },
    });

    if (!set) {
      throw new NotFoundException('Flashcard set not found');
    }

    this.assertAccess(
      { userId: set.userId, organizationId: set.organizationId, visibility: set.visibility },
      userId,
      organizationId,
    );

    const flashcards = await this.prisma.flashcard.findMany({
      where: { flashcardSetId: setId },
      orderBy: { ordering: 'asc' },
      include: {
        legalDocument: {
          select: { id: true, title: true, shortTitle: true, citationText: true },
        },
        digest: {
          select: { id: true, title: true },
        },
      },
    });

    return { set, flashcards };
  }

  private async loadReviewerPackForExport(
    packId: string,
    userId: string,
    organizationId: string,
  ) {
    const pack = await this.prisma.reviewerPack.findUnique({
      where: { id: packId },
      include: {
        items: {
          orderBy: { ordering: 'asc' },
          include: {
            legalDocument: {
              select: {
                id: true,
                title: true,
                shortTitle: true,
                citationText: true,
                documentType: true,
                court: true,
              },
            },
            digest: {
              select: { id: true, title: true, digestType: true },
            },
            section: {
              select: { id: true, sectionLabel: true, sectionType: true },
            },
          },
        },
      },
    });

    if (!pack) {
      throw new NotFoundException('Reviewer pack not found');
    }

    this.assertAccess(
      { userId: pack.creatorUserId, organizationId: pack.organizationId, visibility: pack.visibility },
      userId,
      organizationId,
    );

    return { pack, items: pack.items };
  }

  private getFlashcardSourceRef(card: {
    legalDocument?: { title: string; shortTitle: string | null; citationText: string | null } | null;
    digest?: { title: string } | null;
  }): string | null {
    if (card.legalDocument) {
      return card.legalDocument.citationText ?? card.legalDocument.shortTitle ?? card.legalDocument.title;
    }
    if (card.digest) {
      return card.digest.title;
    }
    return null;
  }

  private getReviewerItemTitle(item: {
    itemType: string;
    legalDocument?: { title: string } | null;
    digest?: { title: string } | null;
    section?: { sectionLabel: string | null; sectionType: string } | null;
  }): string {
    if (item.itemType === 'legal_document' && item.legalDocument) {
      return item.legalDocument.title;
    }
    if (item.itemType === 'digest' && item.digest) {
      return item.digest.title;
    }
    if (item.itemType === 'section' && item.section) {
      return item.section.sectionLabel ?? item.section.sectionType.replace(/_/g, ' ');
    }
    return 'Untitled';
  }

  private getReviewerItemSubtitle(item: {
    itemType: string;
    legalDocument?: { documentType: string; court: string | null; citationText: string | null } | null;
    digest?: { digestType: string } | null;
    section?: { sectionType: string } | null;
  }): string | null {
    if (item.itemType === 'legal_document' && item.legalDocument) {
      return [
        item.legalDocument.documentType?.replace(/_/g, ' '),
        item.legalDocument.court,
        item.legalDocument.citationText,
      ].filter(Boolean).join(' \u2022 ');
    }
    if (item.itemType === 'digest' && item.digest) {
      return item.digest.digestType?.replace(/_/g, ' ') ?? null;
    }
    if (item.itemType === 'section' && item.section) {
      return item.section.sectionType.replace(/_/g, ' ');
    }
    return null;
  }

  private assertAccess(
    entity: { userId: string | null; organizationId: string | null; visibility: string },
    userId: string,
    organizationId: string,
  ) {
    if (entity.visibility === 'public_editorial') return;
    if (entity.visibility === 'private' && entity.userId === userId) return;
    if (entity.visibility === 'org' && entity.organizationId === organizationId) return;
    if (entity.userId === userId) return;
    throw new ForbiddenException('You do not have access to this resource');
  }
}
