export const APP_NAME = 'LIBERTASIAN';
export const APP_DESCRIPTION = 'Philippine Legal AI Platform';

export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  VERIFY_EMAIL: '/verify-email',
  AUTH_CALLBACK: '/auth/callback',
  ONBOARDING: '/onboarding',
  SEARCH: '/search',
  DIGESTS: '/digests',
  DIGEST: (id: string) => `/digests/${id}`,
  SCANS: '/scans',
  SCAN: (id: string) => `/scans/${id}`,
  WORKSPACE: '/workspace',
  WORKSPACE_MATTERS: '/workspace/matters',
  WORKSPACE_MATTER: (id: string) => `/workspace/matters/${id}`,
  WORKSPACE_NOTES: '/workspace/notes',
  WORKSPACE_NOTE: (id: string) => `/workspace/notes/${id}`,
  WORKSPACE_ANNOTATIONS: '/workspace/annotations',
  WORKSPACE_TASKS: '/workspace/tasks',
  WORKSPACE_TASK: (id: string) => `/workspace/tasks/${id}`,
  WORKSPACE_CALENDAR: '/workspace/calendar',
  WORKSPACE_ACTIVITY: '/workspace/activity',
  WORKSPACE_MEMOS: '/workspace/memos',
  WORKSPACE_MEMO: (id: string) => `/workspace/memos/${id}`,
  SETTINGS: '/settings',
  READER: (id: string) => `/reader/${id}`,
  // Study Mode
  STUDY: '/study',
  STUDY_CODALS: '/study/codals',
  STUDY_CODAL: (subject: string) => `/study/codals/${subject}`,
  STUDY_FLASHCARDS: '/study/flashcards',
  STUDY_FLASHCARD: (id: string) => `/study/flashcards/${id}`,
  STUDY_REVIEWER_PACKS: '/study/reviewer-packs',
  STUDY_REVIEWER_PACK: (id: string) => `/study/reviewer-packs/${id}`,
  STUDY_SYLLABUS: '/study/syllabus',
  STUDY_SYLLABUS_SUBJECT: (subject: string) => `/study/syllabus/${subject}`,
  // Admin
  ADMIN: '/admin',
  ADMIN_SOURCES: '/admin/sources',
  ADMIN_SOURCE: (id: string) => `/admin/sources/${id}`,
  ADMIN_REVIEW: '/admin/review',
  ADMIN_FLAGS: '/admin/flags',
  ADMIN_DOCTRINES: '/admin/doctrines',
  ADMIN_DOCTRINE: (id: string) => `/admin/doctrines/${id}`,
  ADMIN_KNOWLEDGE_GRAPH: '/admin/knowledge-graph',
  ADMIN_HEALTH: '/admin/health',
  ADMIN_DUPLICATES: '/admin/duplicates',
  // Community & Marketplace
  COMMUNITY: '/community',
  COMMUNITY_FLASHCARD_SETS: '/community/flashcard-sets',
  COMMUNITY_REVIEWER_PACKS: '/community/reviewer-packs',
  COMMUNITY_DIGESTS: '/community/digests',
  COMMUNITY_CONTRIBUTOR: (userId: string) => `/community/contributors/${userId}`,
  // Sharing (public)
  SHARED: (token: string) => `/shared/${token}`,
} as const;
